### ISSUE TITLE
ios&android模拟器运行下转圈问题

### ISSUE THREAD

**Issue by YuGer26** [virskor/DiscuzQ#106]
例如登录，密码输入错误的话点击登录，提示密码错误，然后就开始全局转圈

**Comment by virskor** [comment]
@YuGer26 这个代码在昨天的push中解除过，git clone 最新的matser代码

**Comment by virskor** [comment]
我关闭了这个issue 如果您有疑问可以重新开启，这个问题已经在最新版master得到处理
