### ISSUE TITLE
大哥啥时候加上上传视频和批量传图功能，谢谢

### ISSUE THREAD

**Issue by ismofei126** [virskor/DiscuzQ#107]
还有，ios查看内容那个抽屉弹出页面，也太安卓了吧。。。。

**Comment by virskor** [comment]
上面的功能后面会添加，但是安卓抽屉这个，后面让你们Build可选吧

**Comment by ismofei126** [comment]
> 上面的功能后面会添加，但是安卓抽屉这个，后面让你们Build可选吧

还有觉得每一次启动app，都是一个空白框架然后获取新数据，能否做成，默认缓存上次浏览的记录到本地默认填充，然后获取到新的内容再替换填充或者往后移动，哪怕网络差一点，一打开就有内容，用户体验好太多了，望大佬采纳。

**Comment by virskor** [comment]
@ismofei126 非常好的建议，在下次的合并中这个优化将被完成

**Comment by virskor** [comment]
@ismofei126 预计Build 59

**Comment by ismofei126** [comment]
等大佬等了好久，都不更新了吗

**Comment by Jason-xy** [comment]
建议加上
1. 评论@功能
2. 在用户名后面显示用户分组
3. 建议可以自定义顶栏Logo，像这样：[Link](https://wpcos-1300629776.cos.ap-chengdu.myqcloud.com/files/20201210/S01210-21110082.jpg)
4. 任务栏消息通知
......

**Comment by virskor** [comment]
批量传图已经增加了
视频现在暂无计划
