### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by pitcomputer** [virskor/DiscuzQ#128]
lib\widgets\editor\toolbar\discuzEditorToolbar.dart里面238行的
`position: BadgePosition(top: 2, right: 0),`要改成
`position: BadgePosition(top: 2, end: 0),`

**Comment by virskor** [comment]
https://github.com/virskor/DiscuzQ/commit/98a6868b5553a993aeb1912f69e611ab378840e1

该故障已经解决，将在后续合并中生效
