### ISSUE TITLE
隐私协议

### ISSUE THREAD

**Issue by pitcomputer** [virskor/DiscuzQ#135]
![S01208-15273021](https://user-images.githubusercontent.com/63231237/101453955-2467d300-396b-11eb-86eb-a1b3b3776b3c.jpg)
![S01208-15280379](https://user-images.githubusercontent.com/63231237/101453959-26ca2d00-396b-11eb-80ec-dbc8084ea3fb.jpg)
第一次启动要同意隐私政策，应用内要有常驻的入口
加油哦⊙∀⊙！

**Comment by virskor** [comment]
已经增加弹窗。备注需要在关于页面也增加

**Comment by pitcomputer** [comment]
需要在关于页面也增加

**Comment by virskor** [comment]
已经添加
