### ISSUE TITLE
   The same comments will be loaded two times

### ISSUE THREAD

**Issue by Jason-xy** [virskor/DiscuzQ#136]
## DiscuzQ Flutter info

Cloned on 12,5,2020

Logos and  domain
## Steps to Reproduce

The same comments will be loaded two times.
1. Open the app
2. Click to enter a post
3. View comments

## Logs

Screen shoot: [Link](https://wpcos-1300629776.cos.ap-chengdu.myqcloud.com/files/20201210/AEDD5166F06B6DFA13F59F2E3085E7D1.jpg)
Screen record; [Link](https://wpcos-1300629776.cos.ap-chengdu.myqcloud.com/files/20201210/S01210-20420433.mp4)
HTTP Logs: [Link](https://wpcos-1300629776.cos.ap-chengdu.myqcloud.com/files/20201210/https-logs.zip)

**Comment by virskor** [comment]
https://github.com/virskor/DiscuzQ/commit/666084871a39a2a61cf33720e606c29783ce9ed9
DONE
